% Saves the data to js file - for the format, see the ordering of the
% fields below... sorry :(

fp = fopen('data.js', 'w');
fprintf(fp, 'var data = [\n');

for ii=1:length(crashcsv)
    fprintf(fp, '[%s,%s,"%s","%s","%s","%s","%s","%s","%s","%s",%.1f,%.1f,%.1f,"%s",%s,"%s"]', ...
    crashcsv(ii).Lat, crashcsv(ii).Long_, ...
    crashcsv(ii).Common_Road_Name(crashcsv(ii).Common_Road_Name ~= '"'), ... % no quotes in here
    crashcsv(ii).Severity, ...
    crashcsv(ii).Total_Truck, ...
    crashcsv(ii).Total_Motor_Cycle, ...
    crashcsv(ii).Total_Pedestrian, ...
    crashcsv(ii).Total_Others_Vehicles, ...
    crashcsv(ii).Total_Heavy_Truck, ...
    crashcsv(ii).Total_Animal, ...
    best_psp_dist(ii), ...
    best_pbn_dist(ii), ...
    best_shared_dist(ii), ...
    crashcsv(ii).ROAD_HIERARCHY, ... % access road, distributor etc.
    crashcsv(ii).SPLI_SPEED_LIMIT, ...
    crashcsv(ii).Cway ... % will be S for single, or L/R (left/right)
    );
    if ii ~= length(crashcsv)-1
        fprintf(fp, ',\n');
    else
        fprintf(fp, '\n');
    end
    
end
fprintf(fp, '\n];');
fclose(fp);
